@echo off
echo ========================================================================================================================
echo Hello, Thanks For Installing Aina-chan Discord Bot
echo ========================================================================================================================
echo This script will install cloudflared to run in your windows, if it doesn't exist I mean...
echo Then it'll automatically run the server and the discord bot...
echo Oh, you're using linux???
echo I'll... Figure it out later...
echo Let's start then...
echo Sorry, I'm just tired...
@echo off
if not exist cloudflared.exe curl -Lo cloudflared.exe https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe
call venv\scripts\activate
start cmd /k "uvicorn main:app --reload --port 5454"
python bot.py